POST http://localhost:3001/api/users 
Content-Type: application/json

{ 
    "username": "hlwinters", 
    "name": "Henry Winters",
    "city": "San Francisco, CA",
    "password": "password",
    "registerDate": "2022-10-29T06:09:20.851Z",
    "color": "#FF715B"
}

###
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "hlwinters",
    "password": "password"
}